# Generated by Django 3.1 on 2021-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(blank=True, choices=[('weight', 'weight'), ('special_message', 'special_message')], max_length=100),
        ),
    ]
