# Generated by Django 3.1 on 2021-05-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210519_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('weight', 'weight'), ('special_message', 'special_message')], max_length=100),
        ),
    ]
