# Generated by Django 3.1 on 2021-05-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210508_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantimy',
            new_name='quantity',
        ),
    ]
